apiVersion: v1
kind: ConfigMap
metadata:
  name: hr-config
  namespace: praveen-ns
data:
  NODE_ENV: "production"
  PORT: "3000"
  MONGO_URI: "mongodb://rootuser:rootpassword@localhost:27017/hr_system?authSource=rootuser"
  DB_NAME: "hr_system"
  MONGO_USERNAME: "rootuser"
  MONGO_PASSWORD: "rootpassword"
  DEFAULT_ADMIN_ID: "project"
  DEFAULT_ADMIN_PASSWORD: "project123"
  LOG_LEVEL: "info"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-app
  namespace: praveen-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hr-app
  template:
    metadata:
      labels:
        app: hr-app
    spec:
      containers:
      - name: hr-app
        image: rishabhmishra01/hr-app-management-system-main-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: hr-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: hr-app-config
              key: PORT
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: hr-app-config
              key: MONGO_URI
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: hr-app-config
              key: DB_NAME
        - name: MONGO_USERNAME
          valueFrom:
            configMapKeyRef:
              name: hr-app-config
              key: MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: hr-app-config
              key: MONGO_PASSWORD
        - name: DEFAULT_ADMIN_ID
          valueFrom:
            configMapKeyRef:
              name: hr-app-config
              key: DEFAULT_ADMIN_ID
        - name: DEFAULT_ADMIN_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: hr-app-config
              key: DEFAULT_ADMIN_PASSWORD
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: hr-app-config
              key: LOG_LEVEL

        - name: DB_NAME
          value: "hr_system"
---
apiVersion: v1
kind: Service
metadata:
  name: hr-service
  namespace: praveen-ns
spec:
  selector:
    app: hr-app
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer
